#!/bin/sh
version=$(cat conf-version)

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s mpdev.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

if [ $copy_src -eq 1 ] ; then
	if [ ! -d ../stage ] ; then
		mkdir ../stage
	fi
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	cd .. # /usr/local/src
	echo "Preparing mpdev-"$version""
	/bin/cp -rp mpdev stage/mpdev-"$version"
	cd stage/mpdev-$version
	echo "Cleaning mpdev-"$version""
	make -s clean
	make -s distclean
	/bin/rm -rf autom4te.cache .deps src/config.log
	cd .. # /usr/local/src/stage
	echo "Archiving mpdev-"$version".tar.gz in `pwd`"
	tar \
		--exclude="mpdev-$version/.git" \
		--exclude="mpdev-$version/debian"  \
		--exclude="mpdev-$version/RCS" \
		-cf - mpdev-"$version" \
		| gzip -c > $rpmbuild/SOURCES/mpdev-"$version".tar.gz
	cd .. # /usr/local/src
	echo "Clearing stage directory"
	/bin/rm -rf stage
fi

dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/mpdev ] ; then
		mdist=$(rpm -qf /usr/bin/mpdev|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $mdist" ] ; then
			mversion=$(rpm -qf /usr/bin/mpdev|cut -d- -f2)
			if [ "$mversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/mpdev | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi

echo -n "Build RPM for mpdev-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	cp mpdev/mpdev.spec /tmp
	sed -i -e "s|^Release: .*|Release: 1.$release%{?dist}|g" /tmp/mpdev.spec
	if [ $? -eq 0 ] ; then
		tmprel=`cat mpdev/conf-release 2>/dev/null`
		if [ ! " $tmprel" = " 1.$release" ] ; then
			echo 1.$release > mpdev/conf-release
			make -s mpdev/mpdev.spec
			cp mpdev/mpdev.spec /tmp
			cd mpdev/debian
			make -s
			cd ../..
		fi
	fi
	rpmbuild -ba --clean /tmp/mpdev.spec
	/bin/rm /tmp/mpdev.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	rpm --addsign $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
	echo -n "RPM lint for mpdev-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		echo mpdev
		rpmlint $rpmbuild/RPMS/$build_arch/mpdev-"$version"-"1.$release".$dist.$build_arch.rpm
		echo ------------------------
		echo mpdev-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/mpdev-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
else
	/bin/rm -rf /tmp/mpdev-"$version"
fi

if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		/bin/rm -f $rpmbuild/SOURCES/mpdev-"$version".tar.gz
	fi
fi
