.TH lastfm-scrobbler 1 "July 3, 2020" "manual"
.SH NAME
.PP
lastfm-scrobbler - lastfm scrobbler

.SH SYNOPSIS
.PP
lastfm-scrobbler [\f[I]option\f[]]

.SH DESCRIPTION
A lastfm.fm (https://last.fm/) scrobbler for \fBmpdev\fR(1) / \fBmpdwatch\fR(1).

lastfm-scrobbler has been cloned from https://goto.pachanka.org/moc-scrobbler.

lastfm-scrobbler is a command line scrobbler for last.fm written as a
bourne shell script.

.EX
USAGE: lastfm-scrobbler [OPTIONS]

OPTIONS:

Help:
    --help
    --help-connect
    --help-scrobble

About:
    --version 
    --about

Connecting:
    --connect --api_key --api_sec

Scrobbling:
    --artist --track --duration

Trackinfo
    --info --artist --track

Love:
    --love --artist --track --duration

UnLove:
    --unlove --artist --track --duration

Update Current Song:
    --update --artist --track --duration

Stop:
    --stop
.EE

.SH Configuration

Run the connect command and follow the instructions:

.EX
$ lastfm-scrobbler --connect
.EE

You need to have your own [last.fm API keys] (https://www.last.fm/api/account/create).

.EX
$ lastfm-scrobbler --connect --api_key="abc123" --api_sec="xyz890"
.EE

After you have added the connection you should have a
`lastfm-scrobbler.conf` file in `~/.config/lastfm-scrobbler/`

Other examples:

.EX
Scrobble a track
$ lastfm-scrobbler --artist="test artist" --album="test album" --track="test track"  --duration=420

Love a track which has been scrobbled
$ lastfm-scrobbler --love --artist="test artist" --album="test album" --track="test track"  --duration=420
.EE

.SH SEE ALSO
mpd(1),
mpdev(1),
mpdwatch(1),
librefm-scrobbler(1)
