.TH librefm-scrobbler 1 "July 3, 2020" "manual"
.SH NAME
.PP
librefm-scrobbler - librefm scrobbler

.SH SYNOPSIS
.PP
librefm-scrobbler [\f[I]option\f[]]

.SH DESCRIPTION
A librefm.fm (https://libre.fm/) scrobbler for \fBmpdev\fR(1) / \fBmpdwatch\fR(1).

librefm-scrobbler has been cloned from https://goto.pachanka.org/moc-scrobbler.

librefm-scrobbler is a command line scrobbler for libre.fm written as a
bourne shell script.

.EX
USAGE: librefm-scrobbler [OPTIONS]

OPTIONS:

Help:
    --help
    --help-connect
    --help-scrobble

About:
    --version 
    --about

Connecting:
    --connect --api_key --api_sec

Scrobbling:
    --artist --track --duration

Love:
    --love --artist --track --duration

Update Current Song:
    --update --artist --track --duration

Stop:
    --stop
.EE

.SH Configuration

Run the connect command and follow the instructions:

.EX
$ librefm-scrobbler --connect
.EE

You need to have your own [last.fm API keys](https://www.last.fm/api/account/create).
Note that the last.fm API key works for libre.fm

.EX
$ librefm-scrobbler --connect --api_key="abc123" --api_sec="xyz890"
.EE

After you have added the connection you should have a
`librefm-scrobbler.conf` file in `~/.config/librefm-scrobbler/`

Other examples:

.EX
Scrobble a track
$ librefm-scrobbler --artist="test artist" --album="test album" \
    --track="test track"  --duration=420

Love a track which has been scrobbled
$ librefm-scrobbler --love --artist="test artist" --album="test album" \
    --track="test track"  --duration=420
.EE

.SH SEE ALSO
mpd(1),
mpdev(1),
mpdwatch(1),
lastfm-scrobbler(1)
