.TH mpdev_update 1 "December 23, 2009" "manual"
.SH NAME
.PP
mpdev_update - Update stats, sticker sqlite db from mpd database
.SH SYNOPSIS
.PP
mpdev_update [\f[I]option\f[]]

.SH DESCRIPTION
.PP
\fBmpdev_update\fR creates/updates stats.db or sticker.db from the
\fBmpd\fR(1) database. It sends the \fIlistinfo\fR command to mpd to
get list of all music files.

.SH OPTIONS
.TP
.B -v
Set verbose output. You can increase verbosity by specifying it multiple times
.RS
.RE

.TP
\fB-i\fR \fIIP\fR
IP address of mpd host if different from localhost
.RS
.RE

.TP
\fB-p\fR \fIport\fR
port on which mpd(1) is listening if different from 6600
.RS
.RE

.TP
\fB-s\fR \fIunix_socket\fR
Unix domain socket in case you don't want to use \fIIP\fR and \fIport\fR
.RS
.RE

.TP
\fB-d\fR \fIdb_file_path\fR
full path to the sqlite3(1) stats database
.RS
.RE

.TP
\fB-D\fR \fI0\fR | \fI1\fR
0 to update stats.db, 1 to update sticker.db
.RS
.RE

.TP
\fB-j\fR 
Puts the journal in volatile memory. This saves disk I/O but at the expense
of database safety and integrity. If the application using SQLite crashes
in the middle of a transaction when the MEMORY journaling mode is set, then
the database file will very likely go corrupt.
.RS
.RE

.TP
\fB-t\fR 
Turns on transaction mode at the beginning. This improves performance. But if
the application crashes in the middle, all new changes will be lost
.RS
.RE

.TP
\fB-S\fR 
Turns Off synchronous mode.
With synchronous OFF, \fBmpdev_update\fR continues without syncing as soon
as it has handed data off to the operating system. In case \fBmpdev_update\fR 
crashes, the data will be safe, but the database might become corrupted if
the operating system crashes or the computer loses power before that data
has been written to the disk. On the other hand, commits can be orders of
magnitude faster with synchronous OFF.
.RS
.RE

.TP
\fB-P\fR 
Print SQL statements used during db creation
.RS
.RE

.SH REPORTING BUGS
.PP
If you find a bug, please report it at https://github.com/mbhangui/mpdev/issues

.SH COPYRIGHT
.PP
Copyright (c) 2020 Manvendra Bhangui <mpdev@indimail.org>
.PD 0
.P
.PD
Free
use of this software is granted under the terms of the GNU General
Public License (GPLv2).
.SH AUTHOR
Manvendra Bhangui <manvendra@indimail.org>

.SH SEE ALSO
mpd(1),
sqlite3(1),
mpdev_cleanup(1),
mpdev(1)
