.TH mpdhist 1
.SH NAME
mpdhist \- Display History of Last played songs

.SH SYNOPSYS
.B mpdhist
--limit
[
.I limit
]

.SH DESCRIPTION
\fBmpdhist\fR displays history of songs plays in descending order of time

.SH OPTIONS

Known values for OPTION are:

.EX
-l \fIlimit\fR | --limit=\fIlimit\fR
  Display last played \fIlimit\fR songs from history

-r | --reverse
  Show earliest played song first

-h | --help

  display this help and exit
.EE

.SH "SEE ALSO"
romprhist(1),
mpdev(1)
