.TH songi 1
.SH NAME
songi \- Display song's information in stats.db

.SH SYNOPSYS
.B songi \fIfilename\fR(s)

.SH DESCRIPTION
\fBsongi\fR displays information about song, namely
.EX
	play_count
	rating
	duration
	last_played
	last_modified
	date_added
	artist
	album
	title
	track
	genre,
	date
	composer
	performer
	disc
	karma
.EE
songi expects audio files to be provided on the commandline. You can use wildcards in filenames.

.SH "SEE ALSO"
karma(1)
