.TH transfer_play 1
.SH NAME
transfer_play \- Transfer mpd playlist from one host to another

.SH SYNOPSYS
.B transfer_play \fIsrc\fR \fIdest\fR

.SH DESCRIPTION
\fBtransfer_play\fR transfers your mpd(1) playlist from one host to another.
It uses the value of \fIstate_file\fR parameter in mpd.conf(5) to get the current
playlist and uses mpc(1) to load the playlist on \fIdest\fR

.SH SEE ALSO
mpd(1),
mpd.conf(5)
