name: mpdev manual trigger

on:
  push:
    paths:
      - '**'
      - .github/workflows/mpdev-obs.yml
      - '!**/doc/*'
      - '!**.md'
      - '!**/mpdev-c-cpp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      name: trigger_obs
      run: |
        # create gpg environment
        echo creating key file
        echo "${{secrets.software_key}}" | gpg --batch --import
        echo "list keys"
        gpg --list-secret-keys --keyid-format LONG
