name: mpdev C/C++ CI

on:
  push:
    paths:
      - '**'
      - .github/workflows/mpdev-c-cpp.yml
      - '!**/debian/*'
      - '!**/mpdev.spec.in'
      - '!**/obs/*'
      - '!**/doc/*'
      - '!**.md'
      - '!**/mpdev-obs.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail; ./default.configure; make; sudo make install-strip

    - name: build_mpdev
      run: |
        cd main; ./default.configure; make
        make clean; /bin/rm -rf .git ../libqmail autom4te.cache
        make -C debian;make mpdev.spec

    - uses: actions/upload-artifact@v2
      with:
        name: mpdev
        path: ${{ github.workspace }}
