name: mpdev C/C++ CI

on:
  push:
    branches: [ master ]
    paths:
      - '**/mpdev/**'
      - .github/workflows/mpdev-c-cpp.yml
      - '!**/mpdev/mpdev.spec.in'
      - '!**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: main

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
          path: ${{ github.workspace }}

    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail; ./default.configure; make; sudo make install-strip

    - name: build_mpdev
      run: cd main; ./default.configure; make
