name: mpdev C/C++ CI

on:
  push:
    paths:
      - '**'
      - .github/workflows/mpdev-c-cpp.yml
      - '!**/debian/*'
      - '!**/mpdev.spec.in'
      - '!**/obs/*'
      - '!**/doc/*'
      - '!**.md'
      - '!**/mpdev-obs.yml'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "ubuntu-latest" ]; then sudo apt-get update;sudo apt-get install libsqlite3-dev; fi
        if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig sqlite3 openssl; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v4
      with:
        path: main

    - name: checkout_qmail
      uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./default.configure; env CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" make; sudo make install-strip
    - name: build_mpdev
      run: |
        cd main; ./default.configure; make
        make clean; /bin/rm -rf .git ../libqmail autom4te.cache
        make -C debian;make mpdev.spec
